imports:
    - { resource: file_storage.yml }

parameters:
#    zerebral_common.example.class: Zerebral\CommonBundle\Example
    kissmetrics.key: secretkey

services:
    kissmetrics:
        class: Zerebral\CommonBundle\KissMetrics\KissMetrics
        arguments: [%kissmetrics.key%]

    kissmetrics.identity_event_handler:
        class: Zerebral\CommonBundle\KissMetrics\EventHandler\IdentityEventHandler
        arguments: [@kissmetrics, @security.context]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }