parameters:
#    zerebral_common.example.class: Zerebral\CommonBundle\Example

services:
    zerebral.file_storage:
        class:      Zerebral\CommonBundle\Component\FileStorage\FileStorageFactory
        arguments:  [%storage%]
