jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    access_decision_manager:
        # Strategy can be: affirmative, unanimous or consensus
        strategy: unanimous
        allow_if_all_abstain: true

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Zerebral\BusinessBundle\Model\User\User: md5
        Zerebral\BusinessBundle\Model\User\Student: md5
        Zerebral\BusinessBundle\Model\User\Teacher: md5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            propel:
                class: Zerebral\BusinessBundle\Model\User\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check

            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
#       - { path: ^/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#       - { path: ^/admin, roles: ROLE_ADMIN }
#       - { path: ^/, roles: ROLE_USER }
