parameters:
#    zerebral_frontend.example.class: Zerebral\FrontendBundle\Example

services:
    zerbral.twig.extension.file_storage:
        class: Zerebral\FrontendBundle\Extension\FileStorageExtension
        arguments:  []
        tags:
            -  { name: twig.extension }
    zerebral.twig.extension.plural:
        class: Zerebral\FrontendBundle\Extension\PluralExtension
        tags:
            -  { name: twig.extension }
    twig.extension.native_functions:
        class: Zerebral\FrontendBundle\Extension\NativeTwigFunction
        tags:
            -  { name: twig.extension }
    twig.extension:
        class: Assetic\Extension\Twig
    zerebral.frontend.login_success_handler:
        class:  Zerebral\FrontendBundle\EventHandler\LoginSuccessHandler
        arguments:  [@router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
