parameters:
#    zerebral_frontend.example.class: Zerebral\FrontendBundle\Example

services:
    twig.extension:
        class: Assetic\Extension\Twig
    zerebral.frontend.login_success_handler:
        class:  Zerebral\FrontendBundle\EventHandler\LoginSuccessHandler
        arguments:  [@router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
