Zerebral\BusinessBundle\Model\User\User:
    constraints:
        - Propel\PropelBundle\Validator\Constraints\UniqueObject:
            fields: email
            groups: [signup]
            message: This email is already taken!
        - Zerebral\CommonBundle\Validator\Constraints\Compare:
            targetField: passwordConfirmation
            sourceField: plainPassword
            comparator: equals
            message: Looks like a mistype. The passwords must match.
            groups: [signup]
    getters:
        firstName:
            - NotBlank:
                groups: [signup]
                message: Enter your first name.
            - MaxLength: 100
        lastName:
            - NotBlank:
                groups: [signup]
                message: Enter your last name.
            - MaxLength: 100
        email:
            - NotBlank:
                groups: [signup]
                message: Email is required.
            - Email:
                groups: [signup]
                message: Doesn't look like a valid email.
            - MaxLength: 100
        avatar:
            - Valid: ~
        plainPassword:
            - NotBlank:
                groups: [signup]
                message: Password is required! You can change it later.
        passwordConfirmation:
            - NotBlank:
                groups: [signup]
        role:
            - Choice:
                groups: [signup]
                choices: [teacher, student]

Zerebral\BusinessBundle\Model\Course\Course:
    constraints:
        - Zerebral\CommonBundle\Validator\Constraints\DateCompare:
            targetField: end
            sourceField: start
            comparator: greater
            message: Course end date should be greater course start date
    getters:
        name:
            - NotBlank:
                message: Enter your course name. You can change it later.
            - MaxLength: 100
        description:
            - NotBlank:
                message: Enter course description.Provide any useful information for students enrolled in this course.
        discipline:
            - NotNull:
                message: Subject area is required
            - Valid: ~
        gradeLevel:
            - Valid: ~
        accessCode:
            - NotBlank:
                groups: [accept_invite]
                message: Access code can't be blank
            - Zerebral\BusinessBundle\Validator\Constraints\AccessCode:
                message: You have to provide a valid (shared by teacher) access code to join the course.
                groups: [accept_invite]
        courseScheduleDays:
            - Valid: ~

Zerebral\BusinessBundle\Model\Course\Discipline:
    constraints:
        - Propel\PropelBundle\Validator\Constraints\UniqueObject:
            fields: [name, teacher_id]
            message: Subject area already exists

Zerebral\BusinessBundle\Model\File\File:
     getters:
         name:
             - NotBlank:
                message: Please, select file for uploading
         uploadedFile:
             - Image:
                 mimeTypes: [image/jpg, image/jpeg, image/png, image/gif]
                 groups: [profile]
             - File: ~

Zerebral\BusinessBundle\Model\Assignment\Assignment:
    getters:
        name:
            - NotBlank:
                message: Enter your assignment name. You can change it later.
            - MaxLength: 200
        description:
            - NotBlank:
                message: Enter assignment description. Any useful information from the student point of view.
        maxPoints:
            - NotBlank:
                message: Max points is required.
            - Type:
                type: integer
                message: Max points should be numerical
            - Range:
                min: 1
                minMessage: Max points should be numerical and positive
                max: 50000
                maxMessage: "{{ value }} is too much for grading (max 50000 allowed)"
        assignmentCategory:
            - NotNull:
                message: Category is required
            - Valid: ~
        files:
            - Valid: ~

Zerebral\BusinessBundle\Model\Assignment\AssignmentCategory:
    constraints:
        - Propel\PropelBundle\Validator\Constraints\UniqueObject:
            fields: [name, teacher_id]
            message: Category already exists

Zerebral\BusinessBundle\Model\Assignment\StudentAssignment:
    getters:
        files:
            - Valid: ~
            - Count:
                min: 1
        grading:
            - Type:
                groups: [grading]
                type: numeric
                message: Grade should be numerical

Zerebral\BusinessBundle\Model\Course\CourseScheduleDay:
    properties:
        week_day:
            - NotBlank:
                message: Day cannot be blank.
        time_from:
            - NotBlank:
                message: Time is required.
        time_to:
            - NotBlank:
                message: Time is required.

Zerebral\BusinessBundle\Model\Material\CourseFolder:
    constraints:
        - Propel\PropelBundle\Validator\Constraints\UniqueObject:
            fields: [course_id,name]
            message: You already have folder with this name
    getters:
        name:
            - NotBlank:
                message: Name can not be blank
            - MaxLength: 255
        course:
            - NotBlank: ~

Zerebral\BusinessBundle\Model\Material\CourseMaterial:
    getters:
        description:
            - MaxLength: 255
        file:
            - Valid: ~
            - NotNull:
                message: File can not be empty
                
Zerebral\BusinessBundle\Model\Attendance\StudentAttendance:
    getters:
        status:
            - Choice:
                choices: [present, tardy, excused]
                message:  Incorrect value.
        comment:
            - MaxLength: 200
                            
Zerebral\BusinessBundle\Model\Feed\FeedItem:
    getters:
        feedContent:
          - Valid: ~
Zerebral\BusinessBundle\Model\Feed\FeedComment:
    getters:
        feedContent:
          - Valid: ~

Zerebral\BusinessBundle\Model\Feed\FeedContent:
    constraints:
        - Zerebral\BusinessBundle\ContentFetcher\Validator\Constraints\FeedContent:
            typeField: type
            linkUrlField: linkUrl
    getters:
        text:
          - NotBlank:
              message: Please write comment text

Zerebral\BusinessBundle\Model\Message\Message:
    getters:
        files:
            - Valid: ~
            - NotNull:
                message: File can not be empty
        body:
            - NotNull:
                groups: [reply, compose]
                message: Message body can not be empty
        subject:
            - NotNull:
                groups: [compose]
                message: Message subject can not be empty
        toId:
            - NotNull:
                groups: [compose]
                message: Recipient can not be empty
        toName:
            - NotNull:
                groups: [compose]
                message: Recipient can not be empty

