Zerebral\BusinessBundle\Model\User\User:
    properties:
        first_name:
            - NotBlank:
                groups: [signup]
                message: Enter your first name.
        last_name:
            - NotBlank:
                groups: [signup]
                message: Enter your last name.
        email:
            - NotBlank:
                groups: [signup]
                message: Email is required.
            - Email:
                groups: [signup]
                message: Doesn't look like a valid email.
        plainPassword:
            - NotBlank:
                groups: [signup]
                message: Password is required! You can change it later.
        passwordConfirmation:
            - NotBlank: ~
        role:
            - Choice:
                groups: [signup]
                choices: [teacher, student]

Zerebral\BusinessBundle\Model\Course\Course:
    properties:
        name:
            - NotBlank:
                message: Enter your course name. You can change it later.
        description:
            - NotBlank:
                message: Enter course description. Any tips useful for students when selecting a course.
        aDiscipline:
            - Valid: ~
        aGradeLevel:
            - Valid: ~

Zerebral\BusinessBundle\Model\Assignment\Assignment:
    properties:
        name:
            - NotBlank:
                message: Enter your assignment name. You can change it later.
        description:
            - NotBlank:
                message: Enter assignment description. Any useful information from the student point of view.
        max_points:
            - NotBlank:
                message: Max ponts is required.
        aAssignmentCategory:
            - Valid: ~