Zerebral\BusinessBundle\Model\User\User:
    constraints:
        - Propel\PropelBundle\Validator\Constraints\UniqueObject:
            fields: email
            groups: [signup]
            message: This email is already taken!
    getters:
        firstName:
            - NotBlank:
                groups: [signup]
                message: Enter your first name.
        lastName:
            - NotBlank:
                groups: [signup]
                message: Enter your last name.
        email:
            - NotBlank:
                groups: [signup]
                message: Email is required.
            - Email:
                groups: [signup]
                message: Doesn't look like a valid email.
        avatar:
            - Valid: ~
        plainPassword:
            - NotBlank:
                groups: [signup]
                message: Password is required! You can change it later.
        passwordConfirmation:
            - NotBlank:
                groups: [signup]
            - Zerebral\FrontendBundle\Form\Validator\SignupConfirmPassword:
                groups: [signup]
        role:
            - Choice:
                groups: [signup]
                choices: [teacher, student]

Zerebral\BusinessBundle\Model\Course\Course:
    getters:
        name:
            - NotBlank:
                message: Enter your course name. You can change it later.
        description:
            - NotBlank:
                message: Enter course description.Provide any useful information for students enrolled in this course.
        discipline:
            - NotNull:
                message: Subject area is required
            - Valid: ~
        gradeLevel:
            - Valid: ~
        accessCode:
            - NotBlank:
                groups: [accept_invite]
                message: Access code can't be blank
            - Zerebral\BusinessBundle\Validator\Constraints\AccessCode:
                message: You have to provide a valid (shared by teacher) access code to join the course.
                groups: [accept_invite]
        courseScheduleDays:
            - Valid: ~

Zerebral\BusinessBundle\Model\Course\Discipline:
    constraints:
        - Propel\PropelBundle\Validator\Constraints\UniqueObject:
            fields: [name, teacher_id]
            message: Subject area already exists

Zerebral\BusinessBundle\Model\File\File:
     getters:
         name:
             - NotBlank: ~
         uploadedFile:
             - Image:
                 groups: [profile]
             - File: ~

Zerebral\BusinessBundle\Model\Assignment\Assignment:
    getters:
        name:
            - NotBlank:
                message: Enter your assignment name. You can change it later.
        description:
            - NotBlank:
                message: Enter assignment description. Any useful information from the student point of view.
        maxPoints:
            - NotBlank:
                message: Max points is required.
            - Type:
                type: integer
                message: Max points should be numerical
            - Range:
                min: 1
                minMessage: Max points should be numerical and positive
                max: 50000
                maxMessage: "{{ value }} is too much for grading (max 50000 allowed)"
        assignmentCategory:
            - NotNull:
                message: Category is required
            - Valid: ~
        files:
            - Valid: ~

Zerebral\BusinessBundle\Model\Assignment\AssignmentCategory:
    constraints:
        - Propel\PropelBundle\Validator\Constraints\UniqueObject:
            fields: [name, teacher_id]
            message: Category already exists

Zerebral\BusinessBundle\Model\Assignment\StudentAssignment:
    getters:
        files:
            - Valid: ~
            - Count:
                min: 1

Zerebral\BusinessBundle\Model\Course\CourseScheduleDay:
    properties:
        week_day:
            - NotBlank:
                message: Day cannot be blank.
        time_from:
            - NotBlank:
                message: Time is required.
        time_to:
            - NotBlank:
                message: Time is required.
