Zerebral\BusinessBundle\Model\User\User:
    properties:
        first_name:
            - NotBlank: ~
        last_name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: ~
        passwordConfirmation:
            - NotBlank: ~
        role:
            - Choice:
                choices: [teacher, student]

Zerebral\BusinessBundle\Model\Course\Course:
    properties:
        name:
            - NotBlank: ~
        description:
            - NotBlank:
                message: Please, put few lines about your course.
        aDiscipline:
            - Valid: ~
        aGradeLevel:
            - Valid: ~