Zerebral\BusinessBundle\Model\User\User:
    constraints:
        - Propel\PropelBundle\Validator\Constraints\UniqueObject:
            fields: email
            groups: [signup]
            message: This email is already taken!
    getters:
        firstName:
            - NotBlank:
                groups: [signup]
                message: Enter your first name.
        lastName:
            - NotBlank:
                groups: [signup]
                message: Enter your last name.
        email:
            - NotBlank:
                groups: [signup]
                message: Email is required.
            - Email:
                groups: [signup]
                message: Doesn't look like a valid email.
        avatar:
            - Valid: ~
        plainPassword:
            - NotBlank:
                groups: [signup]
                message: Password is required! You can change it later.
        passwordConfirmation:
            - NotBlank:
                groups: [signup]
            - Zerebral\FrontendBundle\Form\Validator\SignupConfirmPassword:
                groups: [signup]
        role:
            - Choice:
                groups: [signup]
                choices: [teacher, student]

Zerebral\BusinessBundle\Model\Course\Course:
    getters:
        name:
            - NotBlank:
                message: Enter your course name. You can change it later.
        description:
            - NotBlank:
                message: Enter course description.Provide any useful information for students enrolled in this course.
        discipline:
            - Valid: ~
        gradeLevel:
            - Valid: ~

Zerebral\BusinessBundle\Model\File\File:
    getters:
        uploadedFile:
            - Image:
                groups: [profile]
            - File:
                groups: [assignment]

Zerebral\BusinessBundle\Model\Assignment\Assignment:
    getters:
        name:
            - NotBlank:
                message: Enter your assignment name. You can change it later.
        description:
            - NotBlank:
                message: Enter assignment description. Any useful information from the student point of view.
        maxPoints:
            - NotBlank:
                message: Max ponts is required.
        assignmentCategory:
            - NotNull: ~

#Zerebral\BusinessBundle\Model\Assignment\AssignmentCategory:
#    properties:
#        name:
#            - NotBlank:
#                message: Enter your category name. You can change it later.
