parameters:
#    zerebral_business.example.class: Zerebral\BusinessBundle\Example

services:
    security.course_access_voter:
        class:      Zerebral\BusinessBundle\Security\CourseAccessVoter
        public:     false
        tags:
            -       { name: security.voter }
    security.assignment_access_voter:
        class:      Zerebral\BusinessBundle\Security\AssignmentAccessVoter
        public:     false
        tags:
            -       { name: security.voter }

    security.student_assignment_access_voter:
        class:      Zerebral\BusinessBundle\Security\StudentAssignmentAccessVoter
        public:     false
        tags:
            -       { name: security.voter }

    security.file_access_voter:
        class:      Zerebral\BusinessBundle\Security\FileAccessVoter
        public:     false
        tags:
            -       { name: security.voter }

    zerebral.model_event_subscriber:
        class:      Zerebral\BusinessBundle\EventHandler\ModelEventSubscriber
        tags:
            -       { name: propel.event }

    zerebral.feed_event_subscriber:
        class:      Zerebral\BusinessBundle\EventHandler\FeedEventSubscriber
        tags:
            -       { name: propel.event }

    zerebral.notification_event_subscriber:
        class:      Zerebral\BusinessBundle\EventHandler\NotificationEventSubscriber
        tags:
            -       { name: propel.event }

