parameters:
#    zerebral_business.example.class: Zerebral\BusinessBundle\Example

services:
#    zerebral_business.example:
#        class: %zerebral_business.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
